*Tarea:*

- Cree un programa que calcule el máximo común divisor entre dos números.

In [5]:
%pip install tutormagic
%load_ext tutormagic

Note: you may need to restart the kernel to use updated packages.


In [6]:
%%tutor -k -r

a = 35
b = 30

value_min = min(a, b)

for i in range(1, value_min+1):
    
    if (a%i == 0) and (b%i == 0):
        d_max = i
        
print("El MCD es", d_max)

El MCD es 5


# Tipos de datos en Python




Veamos algunos tipos de datos útiles en Phyton (estos no son todos)

**LISTAS**


Las listas son arreglos de elementos, que pueden ser de distinto tipo. Se definen con corchetes.

In [30]:
Estatura_asistentes = [180.5, 175, 160, 196, 200]

print(Estatura_asistentes)

[180.5, 175, 160, 196, 200]


In [23]:
Estatura_asistentes[4]

200

In [25]:
Estatura_asistentes[0:4] #Slicing

[180, 175, 160, 196]

In [27]:
Estatura_asistentes[-2]

196

In [28]:
sorted(Estatura_asistentes)

[160, 175, 180, 196, 200]

In [9]:
type(Estatura_asistentes)

list

In [11]:
max(Estatura_asistentes)

200

In [12]:
sum(Estatura_asistentes)

911

In [13]:
len(Estatura_asistentes)

5

In [15]:
avg = sum(Estatura_asistentes)/len(Estatura_asistentes)

print(avg)

182.2


In [16]:
my_list = ['a', 'b', 'c']


In [17]:
my_list2 = ['d', 'e', 'f']

In [19]:
my_list + my_list2

['a', 'b', 'c', 'd', 'e', 'f']

In [20]:
combined_list = [1, 'b', 'palabra']

print(combined_list)

[1, 'b', 'palabra']


In [21]:
sum(combined_list)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [31]:
type(Estatura_asistentes[0])

float

In [43]:
Estatura_asistentes = [180.5, 175, 160, 196, 200]

print(Estatura_asistentes)

[180.5, 175, 160, 196, 200]


In [35]:
Estatura_asistentes[0] = 170.5 #Las listas me permiten reemplazar, eliminar y adicionar valores

In [44]:
print(Estatura_asistentes)

[170.5, 175, 160, 196, 200]


In [45]:
# Agregar un nuevo valor al final de la lista

Estatura_asistentes.append(183)

print(Estatura_asistentes)

[180.5, 175, 160, 196, 200, 183, 183]


In [46]:
# Eliminar un elemento

Estatura_asistentes.remove(183)

print(Estatura_asistentes)

[180.5, 175, 160, 196, 200, 183]


**STRING**

Los String, como vimos antes, se definen como listas de carácteres:

In [32]:
mensaje = "Ecopetrol, energía que transforma"
mensaje2 = "Es genial!"

In [33]:
mensaje + mensaje2

'Ecopetrol, energía que transformaEs genial!'

In [35]:
mensaje[0:9]

'Ecopetrol'

In [37]:
mensaje.upper()

'ECOPETROL, ENERGÍA QUE TRANSFORMA'

In [38]:
mensaje.count('e')

4

**TUPLAS**

Las tuplas son arreglos **inmutables** de varios tipos de datos. Es decir que a diferencia de una lista, no podemos agregar, eliminar o modificar los valores dentro de la tupla. Las tuplas las definimos entre paréntesis:


In [48]:
my_tuple = (1, 2, 3, 4)

print(my_tuple)

(1, 2, 3, 4)


In [40]:
type(my_tuple)

tuple

In [49]:
my_tuple = (1, 2, 3, 4, 'mensaje')

print(my_tuple)

(1, 2, 3, 4, 'mensaje')


In [50]:
my_tuple[0] = 3  #En el caso de las tuplas, no es posible modificar los elementos dentro de la tupla.

TypeError: 'tuple' object does not support item assignment

**CONJUNTOS O SETS**

Es una colección de elementos que no están ordenados ni indexados. Para crear estos set utilizamos los corchetes:

In [47]:
my_set = {1, 2, 3}

In [48]:
my_set[0]

TypeError: 'set' object is not subscriptable

In [50]:
my_set2 = {'mensaje', 1, 3, 4}

In [51]:
my_set2

{1, 3, 4, 'mensaje'}

**DICCIONARIOS**

Los Diccionarios en Python es una colección no indexada de datos que se compone de dos partes: 'keys' y 'values'. Son muy utilizados en análisis de datos porque nos permiten relacionar dos tipos de elementos, p. ej. un diccionario inglés-español, los códigos que utiliza cada usuario en una página web, entre otras. Los Diccionarios deben escribirse en llaves de la siguiente forma:

```
Dictionary = {key1:value1, keys2:value2, key3:value3...}
```

Veamos un ejemplo de un Diccionario que contiene palabras la traducción de palabras inglés a español

In [55]:
# Esta es una forma de crear diccionarios

eng2spa = {"Yellow":'Amarillo', 'Blue':'Azul', 'Black': 'Negro'}

eng2spa


{'Yellow': 'Amarillo', 'Blue': 'Azul', 'Black': 'Negro'}

In [56]:
# Esta es otra forma de crear diccionarios

eng2spa = {}

eng2spa["yellow"] = 'Amarillo'
eng2spa["blue"] = 'Azul'
eng2spa["black"] = 'Negro'




In [57]:
eng2spa

{'yellow': 'Amarillo', 'blue': 'Azul', 'black': 'Negro'}

Para los diccionarios, al ser una lista no indexada, no es posible consultar valores por medio de números, se hace por medio de claves.

In [55]:
eng2spa['yellow']

'Amarillo'

In [56]:
eng2spa.keys()

dict_keys(['yellow', 'blue', 'black'])

In [57]:
eng2spa.values()

dict_values(['Amarillo', 'Azul', 'Negro'])

# Funciones

Hasta ahora hemos vimos visto algunas funciones como `print()`, `type()` o `len()` (para las listas), pero no hemos visto su trasfondo.

Como en cualquier otro lenguaje, en *Python* también es posible definir funciones, es decir, secuencias de instrucciones que reciben una o varias entradas, ejecutan algunas operaciones sobre ellos y devuelven uno o varios resultados.

Los valores de entrada, también llamados argumentos o parámetros reales, son necesarios para que la función ejecute la tarea.

Para definir una función:
 

1.   Se usa la palabra clave `def`, seguido por el nombre de la función, entre paréntesis los datos de entrada o parámetros y `:`
2.   Las siguientes líneas serán las intrucciones a ejecutar. Es importante resaltar que todas las intrucciones de una función en Python deben estar indentadas.
3.  Finalmente si la función tiene una salida numérica, debe ir precedida por `return`.



```python
def NOMBRE(LISTA DE ARGUMENTOS):
    INSTRUCCIONES
    return VALOR
```


```python
def NOMBRE(LISTA DE ARGUMENTOS):
    INSTRUCCIONES
    print(VALOR)
```

La línea que contiene el `return` (o `print`) es opcional, pues no todas las funciones deben retornar algo. Por ejemplo, hay algunas que sólo modifican los valores de ciertas variables, por lo que no necesitan retornar o imprimir ningún valor.

In [62]:
def mi_duplicar(x):
    

    x = int(x)
    
    y = x**0.5
    
    return y

In [59]:
mi_duplicar(45)

90

In [60]:
mi_duplicar(300.1)

600.2

Creemos una función que nos permita hacer la conversión de unidades de temperatura, pasar de ºC  a ºF. Recordemos la regla de conversión:

$ºF = 1.8*ºC + 32$

In [66]:
def convtemp(celsius):
    F = 1.8 * celsius +32
    
    return F

In [67]:
convtemp(0)

32.0

Construyamos ahora un programa más avanzado. Un conversor de unidades de temperatura que pueda convertir cualquier escala:

In [3]:
def convtemp(value, scale1, scale2):

    if scale1 == 'c'and scale2 == 'k':
        K = value + 273
        print (value, 'Celsius is', K, 'Kelvin' )


    elif scale1 == 'k'and scale2 == 'c':
            C = value - 273
            print (value, 'Kelvin is', C, 'Celsius' )


    elif scale1 == 'c'and scale2 == 'f':
            F = 1.8 * value + 32 
            print (value, 'Celsius is', F, 'Fahrenheit' )


    elif scale1 == 'f'and scale2 == 'c':
            C = (value - 32) * (5/9)
            print (value, 'Fahrenheit is', C, 'Celsius' )


    elif scale1 == 'k'and scale2 == 'f':
            F = 1.8 * value + 32 
            print (value, 'Kelvin is', F, 'Fahrenheit' )


    elif scale1 == 'f'and scale2 == 'k':
            K = ((value - 32) * (5/9)) + 273
            print (value, 'Fahrenheit is', K, 'Kelvin' )

    else:
            print('Por favor ingrese escalas c, k o f')

In [4]:
convtemp(0,'c','f')

0 Celsius is 32.0 Fahrenheit


In [61]:
convtemp(0,'c','h')

Por favor ingrese escalas c, k o f


Crear funciones propias es una práctica muy común y un aspecto muy importante de los lenguajes de programación. Cuando hemos creado muchas funciones y queremos utilizarlas en otros programas, en otro notebook o simplemente darle nuestras funciones a alguien más podemos crear un **module**.

**Module** es un archivo .py en el cual podemos ubicar todas nuestras funciones y luego, para importarlas utilizamos la siguiente línea de código:

```
from NOMBRE_DE_MI_MODULO import *

```

Una vez importo el modulo que he creado (mi librería) puedo usar las funciones dentro de mi programa. En el caso anterior, la función de conversión de temperatura la guarde en un archivo de texto llamado: mi_libreria.py 



In [2]:
from mi_libreria import *

In [3]:
convtemp(0,'c','k')

0 Celsius is 273 Kelvin


El archivo, lo ubiqué en la misma carpeta donde guardo el notebook donde estoy trabajando. En caso de que desee guardar el módulo en una carpeta distinta, debo configurar el nuevo path de la siguiente forma:


In [5]:
# Al correr esta celda, Python imprime todos los path que están configurados por defecto:

import sys

print(sys.path)

['C:\\Users\\Administrador\\Desktop\\Python_curso_2020', 'C:\\Users\\Administrador\\Anaconda3\\python37.zip', 'C:\\Users\\Administrador\\Anaconda3\\DLLs', 'C:\\Users\\Administrador\\Anaconda3\\lib', 'C:\\Users\\Administrador\\Anaconda3', '', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Administrador\\.ipython']


In [6]:
#para agregar un nuevo path:

sys.path.append('C:\\Users\\Administrador\\Documents\\Ecopetrol') 


print(sys.path)

['C:\\Users\\Administrador\\Desktop\\Python_curso_2020', 'C:\\Users\\Administrador\\Anaconda3\\python37.zip', 'C:\\Users\\Administrador\\Anaconda3\\DLLs', 'C:\\Users\\Administrador\\Anaconda3\\lib', 'C:\\Users\\Administrador\\Anaconda3', '', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\Administrador\\Anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\Administrador\\.ipython', 'C:\\Users\\Administrador\\Documents\\Ecopetrol']


Al agregar el nuevo path (C:\Users\Administrador\Documents\Ecopetrol) ya es posible guardar mis códigos en esta nueva carpeta y Python los podrá importar sin inconvenientes. En este caso, hice una copia de mi_libreria.py y le re-nombre a mi_libreria_test ubicada en Documents\\Ecopetrol:

In [7]:
from mi_libreria_test import *

In [8]:
whos

Variable   Type        Data/Info
--------------------------------
convtemp   function    <function convtemp at 0x000001CB6F57D558>
sys        module      <module 'sys' (built-in)>


*Tarea:*

Cree una función que útil para realizar un cálculo de su área de experticia.

# Algunos Módulos de Python

Python tiene muchas funciones incorporadas que podemos usar. Los módulos son archivos que contienen una colección de funciones relacionadas. Veamos el modulo `math`, utilizado para operaciones matemáticas.


In [9]:
import math 

math.sqrt(49)

7.0

Para importar las funcinones de un módulo debemos utilizar el comando `import` el cual se encarga de leer las funciones dentro del modulo `math`. Para utilizar una función que se encuentre dentro de un módulo, primero debemos poner el nombre del módulo, seguido por un punto y del nombre de la función: `math.sqrt(..)`.


Otras formas de importar modulos:


In [10]:
#En este caso, únicamente importamos la función 'sqrt' del módulo math
from math import sqrt

In [11]:
import math as mt

In [12]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of x but the sign of y.
   

**NumPy**


NumPy es un paquete fundamental de la computación científica en Python. Este paquete de Python se centra en la manipulación de arreglos 1D (vectores), 2D, 3D y nD (matrices). Cuenta además con funcionalidad útiles de algebra lineal,  transformada de Fourier, números aleatorios, entre otras cosas. 

Empecemos con algunas operaciones entre vectores:



In [6]:
import numpy as np

In [11]:
from numpy import arange

In [16]:
a = np.array([1, 2, 3, 4])

print(a)

[1 2 3 4]


In [17]:
b = np.array([6, 7, 8, 9])


In [19]:
np.shape(a)

(4,)

In [20]:
a + b

array([ 7,  9, 11, 13])

In [21]:
a * b

array([ 6, 14, 24, 36])

In [22]:
a * 2

array([2, 4, 6, 8])

In [23]:
#Producto punto

np.dot(a,b)


80

In [7]:
#Matrices

C = np.array([[1, 2, 3], [4, 5, 6]])

print(C)

[[1 2 3]
 [4 5 6]]


In [26]:
C[0,1]

2

In [8]:
#Matrices

C = np.array([[1, 2, 3, 4, 5, 6], [40, 5, 63, 40, 5, 63], [0, 3, 6, 41, 5, 63], [43, 5, 43, 40, 5, 63]])

print(C)

[[ 1  2  3  4  5  6]
 [40  5 63 40  5 63]
 [ 0  3  6 41  5 63]
 [43  5 43 40  5 63]]


In [9]:
C_peq = C[0:3,0:4]

print(C_peq)

[[ 1  2  3  4]
 [40  5 63 40]
 [ 0  3  6 41]]


In [33]:
np.shape(C_peq)

(3, 4)

In [10]:
C_peq.transpose()

array([[ 1, 40,  0],
       [ 2,  5,  3],
       [ 3, 63,  6],
       [ 4, 40, 41]])

In [13]:
zeros_matrix = np.zeros([3,3])

print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
ones_matrix = np.ones([3,3])

print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [1]:
np.random.randint(10)

NameError: name 'np' is not defined

Utilizando números aleatorios